name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug file presence
        run: ls -la
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Sync files to S3 (without deleting existing ones)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: >-
            --acl public-read
            --exclude ".github/*"
            --exclude ".idea/*"
            --exclude ".gitignore"
            --exclude ".git/*"
        env:
          AWS_S3_BUCKET: po2workshop.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1