name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug file presence
        run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Sync files to S3 (without deleting existing ones)
        run: |
          aws s3 sync . s3://po2workshop.com \
            --region us-east-1 \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".idea/*" \
            --exclude ".gitignore"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}